### ISSUE TITLE
Debian inclusion

### ISSUE THREAD

**Issue by Fantu** [linuxmint/captain#5]
I opened an [RFP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1081743) on Debian, but I open also here for more visibility.

I would like it to be included in Debian 13, but I'm afraid I don't have enough time to manage other packages properly, so I'll try to open this one in the hope that someone else is interested.

**Comment by clefebvre** [comment]
Ref: This depends on https://github.com/linuxmint/aptkit/issues/4.
